### ISSUE TITLE
Cannot specify username and password when connecting to PostgreSQL with jdbc-url

### ISSUE THREAD

**Issue by hden** [tomekw/hikari-cp#84]
This works:
- `jdbc:postgresql://127.0.0.1:5432/postgres`

These doesn't
- `jdbc:postgresql://postgres@127.0.0.1:5432/postgres`
  - type: `java.net.UnknownHostException`
  - message: `postgres@127.0.0.1`
- `jdbc:postgresql://postgres:password@127.0.0.1/postgres`
  - type: `java.sql.SQLException`
  - `No suitable driver`
- `jdbc:postgresql://postgres:password@127.0.0.1:5432/postgres`
  - type: `java.net.UnknownHostException`
  - message: `postgres:password@127.0.0.1`

## Environments

Clojure v1.10
Postgres 11

```
[hikari-cp "2.7.1"]
[org.postgresql/postgresq "42.2.5"]
```

**Comment by jstepien** [comment]
Thank you for reporting the issue, @hden. The behaviour you describe appears to be reproducible using HikariCP itself and is not specific to the Clojure wrapper.

```java
import com.zaxxer.hikari.*;

class Test {
    public static void main(String args[]) {
        var config = new HikariConfig();
        config.setJdbcUrl(args[0]);
        var datasource = new HikariDataSource(config);
    }
}
```

Just as you describe, `java Test jdbc:postgresql://127.0.0.1:5432/postgres` works and all the other JDBC URLs result in errors.

Since hikari-cp is just a thin wrapper around the Java library, there's not much we can do to address this behaviour. Consider reporting the problem upstream.

**Comment by hden** [comment]
My bad. It should be `jdbc:postgresql://host/database?user=fred&password=secret&...`.

See https://github.com/brettwooldridge/HikariCP/issues/1402#issuecomment-507811747
